Add WP-CLI early terminating calls
szepeviktor/phpstan-wordpress pull request #23
Opened 2020-09-20 07:59 UTC by dingo-d

The ones that have `exit()` calls in them.

This is a fix for #22 

I'm not sure if the functions from the [utils.php](https://github.com/wp-cli/wp-cli/blob/master/php/utils.php) be included as well. Those are utility functions, not sure if they are used in userland code, or just for internal WP-CLI purposes.

2020-09-20 08:15 UTC, szepeviktor approved these changes

2020-09-20 08:15 UTC, szepeviktor commented on extension.neon
> +            - WP_CLI::runcommand
I think these commands terminate execution only with a complex condition.

https://github.com/wp-cli/wp-cli/blob/d7df11b43e9ece6990ac42371aadac2cbd9d6554/php/class-wp-cli.php#L1270-L1271

`earlyTerminatingMethodCalls` is for methods unconditionally terminating execution.

Even if you write a PHPStan service for `WP_CLI::runcommand` you cannot figure out what the command's exit status will be.
:) So never enable `exit_error` to keep your code testable.

2020-09-20 08:16 UTC, szepeviktor requested changes
Please remove those two.

2020-09-20 08:19 UTC, szepeviktor commented on extension.neon
> +            - WP_CLI::runcommand
Added this warning to the README

2020-09-21 07:23 UTC, dingo-d commented
@szepeviktor Thanks for the clarification, wasn't sure if any command should be added. I've removed those two 👍

2020-09-21 07:38 UTC, szepeviktor commented
Thank you.

2020-09-21 07:38 UTC, merged

2020-09-21 07:43 UTC, szepeviktor commented
https://github.com/szepeviktor/phpstan-wordpress/releases/tag/v0.6.4 🎉